#!/usr/bin/env node
'use strict';
require('babel-polyfill');

(async function run(...args) {
  const {Server} = require('ws');
  const puppeteer = require('puppeteer');
  const run = require('./chrome_evaluate');

  const [,,port = 8888, query] = args;
  let url = `http://localhost:${port}/consoleRunner`;
  if (query) url += `/?${query}`;

  let server;

  try {
    server = new Server({port: 9876});
    server.on('connection', socket => socket.on('message', console.error));

    let browser;
    try {
      browser = await puppeteer.launch();
      const page = await browser.newPage();
      await page.on('console', ({args}) => {
        console.error(JSON.stringify({id: ':consoleMessage', message: args.join('\n')}));
      });

      await page.goto(url);
      await page.evaluate(run);
    } finally {
      browser && browser.close();
    }
  } finally {
    server.close();
  }
})(...process.argv);
